name: Auto Releases

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6

    - name: Generate tag
      id: tag
      run: echo "TAG=v$(date +'%Y.%m')" >> $GITHUB_OUTPUT

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag.outputs.TAG }}
        name: Release ${{ steps.tag.outputs.TAG }}
