name: jmusicbot CI

on:
  workflow_dispatch:

env:
  GITHUB_USERNAME: cwlu2001
  GITHUB_REPOSITORY: docker-jmusicbot
  GITHUB_README: README.md
  DOCKER_USERNAME: cwlu2001
  DOCKER_REPOSITORY: jmusicbot
  DOCKER_IMAGE_ARCH: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get metadata
        id: get_metadata
        run: |
          curl -s https://api.github.com/repos/jagrosh/MusicBot/releases/latest > response
          TAG=$(jq -r '.tag_name' response)
          DL_URL=$(jq -r '.assets[0].browser_download_url' response)
          echo tag=$TAG >> $GITHUB_OUTPUT
          echo dl_url=$DL_URL >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          repository: ${{ env.GITHUB_USERNAME }}/${{ env.GITHUB_REPOSITORY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}
          labels: |
            org.opencontainers.image.title=jmusicbot
            org.opencontainers.image.url=https://github.com/cwlu2001/docker-jmusicbot
            org.opencontainers.image.source=https://github.com/cwlu2001/docker-jmusicbot
            org.opencontainers.image.version=${{ steps.get_metadata.outputs.tag }}
          tags: |
            latest
            ${{ steps.get_metadata.outputs.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ env.DOCKER_IMAGE_ARCH }}
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DL_URL=${{ steps.get_metadata.outputs.dl_url }}

      - name: Update Docker Hub README
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}
          readme-filepath: ${{ env.GITHUB_README }}
