name: selfsigned-ssl CI

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

env:
  GITHUB_USERNAME: cwlu2001
  GITHUB_REPOSITORY: docker-selfsigned-ssl
  GITHUB_TAG: ${{ inputs.tag }}
  GITHUB_README: README.md
  DOCKER_USERNAME: cwlu2001
  DOCKER_REPOSITORY: selfsigned-ssl
  DOCKER_IMAGE_ARCH: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.GITHUB_USERNAME }}/${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_TAG }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}
          labels: |
            org.opencontainers.image.title=selfsigned-ssl
            org.opencontainers.image.url=https://github.com/cwlu2001/docker-selfsigned-ssl
            org.opencontainers.image.source=https://github.com/cwlu2001/docker-selfsigned-ssl
          tags: |
            type=pep440,pattern={{version}},value=${{ env.GITHUB_TAG }},enable=${{ startsWith(github.ref, 'v') }}
            type=raw,value=latest,enable=${{ startsWith(env.GITHUB_TAG, 'v') }}
            type=raw,value=${{ env.GITHUB_TAG }},enable=${{ !startsWith(env.GITHUB_TAG, 'v') }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ env.DOCKER_IMAGE_ARCH }}
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Docker Hub README
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}
          readme-filepath: ${{ env.GITHUB_README }}
