name: vlmcsd CI

on:
  workflow_dispatch:
  schedule:
    - cron: '3 3 * * *'

env:
  GITHUB_USERNAME: cwlu2001
  GITHUB_REPOSITORY: docker-vlmcsd
  DOCKER_USERNAME: cwlu2001
  DOCKER_REPOSITORY: vlmcsd
  DOCKER_IMAGE_ARCH: linux/amd64,linux/arm64
  GITHUB_README: README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.GITHUB_USERNAME }}/${{ env.GITHUB_REPOSITORY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}
          labels: |
            org.opencontainers.image.description=Vlmcsd is a MS Emulator
            org.opencontainers.image.source=https://github.com/cwlu2001/docker-vlmcsd
            org.opencontainers.image.title=vlmcsd
            org.opencontainers.image.url=https://github.com/cwlu2001/docker-vlmcsd
          tags: |
            latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ env.DOCKER_IMAGE_ARCH }}
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Docker Hub README
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}
          readme-filepath: ${{ env.GITHUB_README }}
